//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TempAndSortGUI.TempAndSortService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="TempAndSortService.TempAndSorting")]
    public interface TempAndSorting {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/TempAndSorting/c2f", ReplyAction="http://tempuri.org/TempAndSorting/c2fResponse")]
        int c2f(int c);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/TempAndSorting/c2f", ReplyAction="http://tempuri.org/TempAndSorting/c2fResponse")]
        System.Threading.Tasks.Task<int> c2fAsync(int c);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/TempAndSorting/f2c", ReplyAction="http://tempuri.org/TempAndSorting/f2cResponse")]
        int f2c(int f);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/TempAndSorting/f2c", ReplyAction="http://tempuri.org/TempAndSorting/f2cResponse")]
        System.Threading.Tasks.Task<int> f2cAsync(int f);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/TempAndSorting/sort", ReplyAction="http://tempuri.org/TempAndSorting/sortResponse")]
        string sort(string s);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/TempAndSorting/sort", ReplyAction="http://tempuri.org/TempAndSorting/sortResponse")]
        System.Threading.Tasks.Task<string> sortAsync(string s);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface TempAndSortingChannel : TempAndSortGUI.TempAndSortService.TempAndSorting, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class TempAndSortingClient : System.ServiceModel.ClientBase<TempAndSortGUI.TempAndSortService.TempAndSorting>, TempAndSortGUI.TempAndSortService.TempAndSorting {
        
        public TempAndSortingClient() {
        }
        
        public TempAndSortingClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public TempAndSortingClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TempAndSortingClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TempAndSortingClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public int c2f(int c) {
            return base.Channel.c2f(c);
        }
        
        public System.Threading.Tasks.Task<int> c2fAsync(int c) {
            return base.Channel.c2fAsync(c);
        }
        
        public int f2c(int f) {
            return base.Channel.f2c(f);
        }
        
        public System.Threading.Tasks.Task<int> f2cAsync(int f) {
            return base.Channel.f2cAsync(f);
        }
        
        public string sort(string s) {
            return base.Channel.sort(s);
        }
        
        public System.Threading.Tasks.Task<string> sortAsync(string s) {
            return base.Channel.sortAsync(s);
        }
    }
}
